export const TABLE_TURMA = "TURMA"
export const TABLE_ESTUDANTE = "ESTUDANTE"
export const TABLE_PASSATEMPO = "PASSATEMPO"
export const TABLE_ESTUDANTE_PASSATEMPO = "ESTUDANTE_PASSATEMPO"
export const TABLE_DOCENTE = "DOCENTE"
export const TABLE_ESPECIALIDADE = "ESPECIALIDADE"
export const TABLE_DOCENTE_ESPECIALIDADE = "DOCENTE_ESPECIALIDADE"

