POST http://localhost:3003/user/create
Content-Type: application/json

{
    "name": "Cassiane",
    "email": "cassisrxx@gmail.com",
    "nickname": "cassiesrxx",
    "password": "senha123"
}


POST http://localhost:3003/task
Content-Type: application/json

{
    "title" : "ir no mercado", 
    "description" : "comprar comida pra janta",
    "deadline" : "15/10",
    "authorId": "1671128229825"
}
